skillMetadata:
  sections:
    - name: Skill Data Sources
      fields:
        - name: weather_skill
          type: text
          label: Weather
          value: skill-weather.neon
        - name: datetime_skill
          type: text
          label: Date and Time
          value: date-time.neon
        - name: examples_skill
          type: text
          label: Examples
          value: about.neon
    - name: Personalization
      fields:
        - name: wallpaper
          type: text
          label: Wallpaper
          value: default.jpg